let massive = [{
    ispopular: true,
    image: 'files/Italy, Venice.png',
    headline: 'Италия, Венеция',
    text: '9 дней | 11 дней с поездкой на полуостров Сорренто',
    price: 155000,
    priceCross: 177000,
    button: 'Выбрать',
    id: 'product_italy_venice',
},
{
    ispopular: true,
    image: 'files/Italy, Manola.png',
    headline: 'Италия, Манарола',
    text: '12 дней | 14 дней с поездкой в Рим',
    price: 200000,
    priceCross: 230000,
    button: 'Выбрать',
    id: 'product_italy_manola',
},
{
    ispopular: true,
    image: 'files/Paris.png',
    headline: 'Париж',
    text: '9 дней | 12 дней  поездка в Нормандию и Париж',
    price: 138000,
    priceCross: 150000,
    button: 'Выбрать',
    id: 'product__paris',
},
{
    ispopular: false,
    image: 'files/London.png',
    headline: 'Лондон',
    text: '9 дней | 11 дней с поездкой в Париж',
    price: 285000,
    priceCross: 295000,
    button: 'Выбрать',
    id: 'product__london',
},
{
    ispopular: false,
    image: 'files/Brazil, Rio.png',
    headline: 'Бразилия, Рио',
    text: 'Рио, водопады Игуасу и Буэнос-Айрес',
    price: 225000,
    priceCross: 240000,
    button: 'Выбрать',
    id: 'product_brazil_rio',
},
{
    ispopular: false,
    image: 'files/Helsinki.png',
    headline: 'Хельсинки',
    text: 'Скандинавия: столицы и фьорды',
    price: 215000,
    priceCross: '230 000 ',
    button: 'Выбрать',
    id: 'product__helsinki',
},
{
    ispopular: false,
    image: 'files/Italy, Rome.png',
    headline: 'Италия, Рим',
    text: '11 дней | 14 дней с поездкой в Мадрид',
    price: 200000,
    priceCross: '230 000 ',
    button: 'Выбрать',
    id: 'product_italy_rome',
},
{
    ispopular: false,
    image: 'files/Spain.png',
    headline: 'Тур по Испании',
    text: '14 дней | 16 дней с поездкой в Барселону',
    price: 200000,
    priceCross: '210 000 ',
    button: 'Выбрать',
    id: 'product__spain',
},
{
    ispopular: false,
    image: 'files/Alaska.png',
    headline: 'Аляска',
    text: 'Национальный парк Денали и круиз по дикой Аляске',
    price: 300000,
    priceCross: '310 000 ',
    button: 'Выбрать',
    id: 'product__alaska',
},]